const watches = [
  {
    id: 1,
    nom: "Santos",
    description:
      "Montre Santos par Cartier - Élégance intemporelle et raffinement.",
    prix: 7500.0,
    stock: 10,
    marque: "Cartier",
    image_url:
      "https://www.cartier.com/variants/images/44733502651435035/img1/w1242_tpadding12.jpg",
    categories: [
      "Luxe",
      "Automatique",
      "Acier inoxydable",
      "Cuir",
      "Date",
      "Blanc",
      "Haut de gamme",
      "Moyen",
      "Unisexe",
    ],
    created: new Date(),
  },

  {
    id: 2,
    nom: "Seamaster",
    description:
      "Montre Seamaster par Omega - Une icône de l'horlogerie de plongée.",
    prix: 5200.0,
    stock: 15,
    marque: "Omega",
    image_url:
      "https://www.omegawatches.com/variants/images/123123123123/img1/w1242_tpadding12.jpg",
    categories: [
      "Sport",
      "Automatique",
      "Acier inoxydable",
      "Bracelet en caoutchouc",
      "Résistance à l'eau",
      "Bleu",
      "Haut de gamme",
      "Moyen",
      "Hommes",
    ],
    created: new Date(),
  },
  {
    id: 3,
    nom: "Datejust",
    description:
      "Montre Datejust par Rolex - Élégance classique et sophistication.",
    prix: 9500.0,
    stock: 8,
    marque: "Rolex",
    image_url:
      "https://www.rolex.com/variants/images/987654321000/img1/w1242_tpadding12.jpg",
    categories: [
      "Classique",
      "Automatique",
      "Or",
      "Bracelet en acier inoxydable",
      "Date",
      "Blanc",
      "Haut de gamme",
      "Moyen",
      "Unisexe",
    ],
    created: new Date(),
  },
  {
    id: 4,
    nom: "G-Shock",
    description:
      "Montre G-Shock par Casio - Robuste, fiable et prête pour l'action.",
    prix: 120.0,
    stock: 20,
    marque: "Casio",
    image_url:
      "https://www.casio.com/variants/images/456789012345/img1/w1242_tpadding12.jpg",
    categories: [
      "Sport",
      "Quartz",
      "Plastique",
      "Bracelet en résine",
      "Résistance aux chocs",
      "Noir",
      "Entrée de gamme",
      "Moyen",
      "Unisexe",
    ],
    created: new Date(),
  },
  {
    id: 5,
    nom: "Carrera",
    description:
      "Montre Carrera par Tag Heuer - Performance ultime et design avant-gardiste.",
    prix: 6800.0,
    stock: 12,
    marque: "Tag Heuer",
    image_url:
      "https://www.tagheuer.com/variants/images/543210987654/img1/w1242_tpadding12.jpg",
    categories: [
      "Sport",
      "Automatique",
      "Acier inoxydable",
      "Bracelet en acier",
      "Chronographe",
      "Noir",
      "Haut de gamme",
      "Moyen",
      "Hommes",
    ],
    created: new Date(),
  },
  {
    id: 6,
    nom: "Presage",
    description:
      "Montre Presage par Seiko - Artisanat japonais et élégance contemporaine.",
    prix: 550.0,
    stock: 18,
    marque: "Seiko",
    image_url:
      "https://www.seikowatches.com/variants/images/135792468000/img1/w1242_tpadding12.jpg",
    categories: [
      "Classique",
      "Automatique",
      "Acier inoxydable",
      "Bracelet en cuir",
      "Date",
      "Blanc",
      "Milieu de gamme",
      "Moyen",
      "Unisexe",
    ],
    created: new Date(),
  },
  {
    id: 7,
    nom: "Nautilus",
    description:
      "Montre Nautilus par Patek Philippe - Un chef-d'œuvre de l'horlogerie de luxe.",
    prix: 28000.0,
    stock: 5,
    marque: "Patek Philippe",
    image_url:
      "https://www.patek.com/variants/images/987654321987/img1/w1242_tpadding12.jpg",
    categories: [
      "Luxe",
      "Automatique",
      "Or",
      "Bracelet en acier inoxydable",
      "Date",
      "Bleu",
      "Haut de gamme",
      "Moyen",
      "Hommes",
    ],
    created: new Date(),
  },
  {
    id: 8,
    nom: "Eco-Drive",
    description:
      "Montre Eco-Drive par Citizen - Technologie solaire et design moderne.",
    prix: 300.0,
    stock: 25,
    marque: "Citizen",
    image_url:
      "https://www.citizen.com/variants/images/789012345678/img1/w1242_tpadding12.jpg",
    categories: [
      "Décontracté",
      "Quartz",
      "Acier inoxydable",
      "Bracelet en acier",
      "Résistance à l'eau",
      "Noir",
      "Milieu de gamme",
      "Moyen",
      "Unisexe",
    ],
    created: new Date(),
  },
  {
    id: 9,
    nom: "Vintage",
    description: "Montre Vintage par Fossil - Un hommage au style intemporel.",
    prix: 180.0,
    stock: 15,
    marque: "Fossil",
    image_url:
      "https://www.fossil.com/variants/images/246813579000/img1/w1242_tpadding12.jpg",
    categories: [
      "Vintage",
      "Quartz",
      "Acier inoxydable",
      "Bracelet en cuir",
      "Date",
      "Blanc",
      "Décontracté",
      "Entrée de gamme",
      "Unisexe",
    ],
    created: new Date(),
  },
]

module.exports = watches
